AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: SAM Template Copy from S3 to App
Parameters:
  ArtifactsBucket:
    Type: 'AWS::SSM::Parameter::Value<String>'
    Default: 'ArtifactsBucket'
  RawBucketName:
    Type: 'AWS::SSM::Parameter::Value<String>'
    Default: 'RawBucketName'
  ExchangeBucketName:
    Type: 'AWS::SSM::Parameter::Value<String>'
    Default: 'ExchangeBucketName'
  SnowflakeExternalStageBucketName:
    Type: 'AWS::SSM::Parameter::Value<String>'
    Default: 'SnowflakeExternalStageBucketName'
  DgoExchangeBucketName:
    Type: 'AWS::SSM::Parameter::Value<String>'
    Default: 'DgoExchangeBucketName'
  JarFileName:
    Type: 'AWS::SSM::Parameter::Value<String>'
    Default: '/_env/artifacts/s3/path/S3CopyJar'
  Version:
    Type: 'AWS::SSM::Parameter::Value<String>'
    Default: '/_env/VersionOfJar'
Conditions:
  CreateDevStg: !Or [!Equals [!Ref "Env" dev], !Equals [!Ref "Env", stg]]
  CreateProd: !Equals [!Ref "Env", prod]

Mappings: 
  Environment:
    stg:
      Value: staging
    dev:
      Value: development
    prod:
      Value: production
Resources:
  S3CopyApp:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "lambda-${Env}-s3-copy-app-${RegionCode}-all"
      Handler: com.generic.s3.copy.GenericS3Copier::handleRequest
      Runtime: java8
      Timeout: 900
      MemorySize: 512
      Description: s3 copy app
      CodeUri:
        Bucket: !Ref ArtifactsBucket
        key: !Sub ${JarFileName}
      Role: !If [CreateDevStg!GetAtt S3CopyAppRole.Arn, !GetAtt S3ProdCopyAppRole.Arn]
      Environment:
        Variables:
          GLOBAL_ENDPOINT_REGION: us-east-1
          HIST_RUN_TABLE: !Sub "${Env}_ETLStateLog"
          LAST_RUN_TABLE: !Sub "${Env}_ETLStateLastRunLog"
      Tags:
        version: !Sub ${Version}
        environment: !FindInMap
          - Environment
          - !Ref Env
          - Value
      S3CopyAppRole:
    Type: "AWS::IAM::Role"
    Condition: CreateDevStg
    Properties:
      RoleName: !Sub aws-sam-S3CopyAppRole-${Env}
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
              - lambda.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Policies:
        - PolicyName:  !Sub S3CopyAppPolicy-${Env}
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
            - Effect: Allow
              Action: 
              - ssm: GetParameters
              - ssm: GetParameter
              - ssm: GetparametersByPath
              Resource:
                Fn::Sub:
                - arn:${AWS::Partition}:ssm:${AWS::Region}:${AWS::AccountId}:parameter/${parameterName}
                - parameterName: !Sub "${Env}/*"

           - Effect: Allow
             Action:
               - dynamodb: GetItem
               - dynamodb: DeleteItem
               - dynamodb: PutItem
               - dynamodb: Scan
               - dynamodb: Query
               -  dynamodb: UpdateItem
               -  dynamodb: BatchWriteItem
               - dynamodb: BatchGetItem
              - dynamodb: DescribeTable
              - dynamodb: ConditionCheckItem
              - dynamodb: UpdateTable
            Resource:
              - !Sub
              - arn:${AWS::Partition}:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${tableName}
              - tableName: "*"

            - Effect: Allow
              Action:
              - s3:GetObject
              - s3:ListBucket
              - s3:GetBucketLocation
              - s3:GetObjectVersion
              - s3:PutObject
              - s3:PutObjectAcl
              - s3:GetLifecycleConfiguration
              - s3:PutLifecycleConfiguration
              - s3:DeleteObject
              Resource:
              - Fn::Sub:
                - arn:${AWS::Partition}:s3:::${bucketName}
                - bucketName:
                    Ref: RawBucketName
              - Fn::Sub:
                - arn:${AWS::Partition}:s3:::${bucketName}/*
                - bucketName:
                    Ref: RawBucketName

            - Effect: Allow
              Action:
              - s3:GetObject
              - s3:ListBucket
              - s3:GetBucketLocation
              - s3:GetObjectVersion
              - s3:PutObject
              - s3:PutObjectAcl
              - s3:GetLifecycleConfiguration
              - s3:PutLifecycleConfiguration
              - s3:DeleteObject
              Resource:
              - Fn::Sub:
                - arn:${AWS::Partition}:s3:::${bucketName}
                - bucketName:
                    Ref: ExchangeBucketName
              - Fn::Sub:
                - arn:${AWS::Partition}:s3:::${bucketName}/*
                - bucketName:
                    Ref: ExchangeBucketName
              - Fn::Sub:
                - arn:${AWS::Partition}:s3:::${bucketName}
                - bucketName:
                    Ref: SnowflakeExternalStageBucketName
              - Fn::Sub:
                - arn:${AWS::Partition}:s3:::${bucketName}/*
                - bucketName:
                    Ref: SnowflakeExternalStageBucketName
              - Fn::Sub:
                - arn:${AWS::Partition}:s3:::${bucketName}
                - bucketName:
                    Ref: DgoExchangeBucketName
              - Fn::Sub:
                - arn:${AWS::Partition}:s3:::${bucketName}/*
                - bucketName:
                    Ref: ExchangeBucketName

             - Effect: Allow
               Action:
                - s3:GetObject
                - s3:ListBucket
                - s3:GetBucketLocation
                - s3:GetObjectVersion
              Resource:
                - Fn::Sub:
                  - arn:${AWS::Partition}:s3:::${bucketName}
                  - bucketName: !Sub s3-${Env}-data-exchange-bucket-${RegionCode}-all
                - Fn::Sub:
                  - arn:${AWS::Partition}:s3:::${bucketName}
                  - bucketName: !Sub s3-${Env}-data-exchange-bucket-${RegionCode}-all/*

            - Effect: Allow
              Action:
                - cloudwatch:PutMetricData
              Resource: "*"

            - Effect: Allow
              Action:
                - logs:*
              Resource: arn:aws:logs:*:*:*

  S3ProdCopyAppRole:
    Type: "AWS::IAM::Role"
    Condition: CreateProd
    Properties:
      RoleName: !Sub aws-sam-S3CopyAppRole-${Env}
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
              - lambda.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Policies:
        - PolicyName:  !Sub S3CopyAppPolicy-${Env}
          PolicyDocument:
            Version: "2012-10-17"
            Statement:

            - Effect: Allow
              Action:
              - ssm:DescribeParameters
              Resource: "*"
            - Effect: Allow
              Action:
              - ssm:GetParameters
              - ssm:GetParameter
              - ssm:GetParametersByPath
              Resource:
                Fn::Sub:
                - arn:${AWS::Partition}:ssm:${AWS::Region}:${AWS::AccountId}:parameter/${parameterName}
                - parameterName: !Sub "${Env}/*"

            - Effect: Allow
              Action:
              - dynamodb:GetItem
              - dynamodb:DeleteItem
              - dynamodb:PutItem
              - dynamodb:Scan
              - dynamodb:Query
              - dynamodb:UpdateItem
              - dynamodb:BatchWriteItem
              - dynamodb:BatchGetItem
              - dynamodb:DescribeTable
              - dynamodb:ConditionCheckItem
              - dynamodb:UpdateTable
              Resource:
              - !Sub
                - arn:${AWS::Partition}:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${tableName}
                - tableName: "*"

            - Effect: Allow
              Action:
              - s3:GetObject
              - s3:ListBucket
              - s3:GetBucketLocation
              - s3:GetObjectVersion
              - s3:PutObject
              - s3:PutObjectAcl
              - s3:GetLifecycleConfiguration
              - s3:PutLifecycleConfiguration
              - s3:DeleteObject
              Resource:
              - Fn::Sub:
                - arn:${AWS::Partition}:s3:::${bucketName}
                - bucketName:
                    Ref: RawBucketName
              - Fn::Sub:
                - arn:${AWS::Partition}:s3:::${bucketName}/*
                - bucketName:
                    Ref: RawBucketName

            - Effect: Allow
              Action:
              - s3:GetObject
              - s3:ListBucket
              - s3:GetBucketLocation
              - s3:GetObjectVersion
              - s3:PutObject
              - s3:PutObjectAcl
              - s3:GetLifecycleConfiguration
              - s3:PutLifecycleConfiguration
              - s3:DeleteObject
              Resource:
              - Fn::Sub:
                - arn:${AWS::Partition}:s3:::${bucketName}
                - bucketName:
                    Ref: ExchangeBucketName
              - Fn::Sub:
                - arn:${AWS::Partition}:s3:::${bucketName}/*
                - bucketName:
                    Ref: ExchangeBucketName
              - Fn::Sub:
                - arn:${AWS::Partition}:s3:::${bucketName}
                - bucketName:
                    Ref: SnowflakeExternalStageBucketName
              - Fn::Sub:
                - arn:${AWS::Partition}:s3:::${bucketName}/*
                - bucketName:
                    Ref: SnowflakeExternalStageBucketName
              - Fn::Sub:
                - arn:${AWS::Partition}:s3:::${bucketName}
                - bucketName:
                    Ref: DgoExchangeBucketName
              - Fn::Sub:
                - arn:${AWS::Partition}:s3:::${bucketName}/*
                - bucketName:
                    Ref: DgoExchangeBucketName

            - Effect: Allow
              Action:
                - cloudwatch:PutMetricData
              Resource: "*"

            - Effect: Allow
              Action:
                - logs:*
              Resource: arn:aws:logs:*:*:*

